//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactuses.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cactuses_Exhibitions
    {
        public int ID { get; set; }
        public int CactusID { get; set; }
        public int ExhibitionID { get; set; }
    
        public virtual Cactuses Cactuses { get; set; }
        public virtual Exhibitions Exhibitions { get; set; }
    }
}
