//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactuses.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MDK_RPM_CactusEntities : DbContext
    {
        public MDK_RPM_CactusEntities()
            : base("name=MDK_RPM_CactusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cactuses> Cactuses { get; set; }
        public virtual DbSet<Cactuses_Exhibitions> Cactuses_Exhibitions { get; set; }
        public virtual DbSet<Exhibitions> Exhibitions { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
